### ISSUE TITLE
Sometimes my fonts are colored

### ISSUE THREAD

**Issue by david-hurtado-galac** [madskristensen/RainbowBraces#33] opened 2022-09-30 12:25 UTC
**Describe the bug**
After install the extension frecuently, my fonts are colored  with extrange colors.

**To Reproduce**
1. Install extension (Set VS2022 to Dark Theme)
2. Create a new variable
3. Make a reference to other method

**Screenshots**
I have added and screen to see this behavor!

**Additional context**
I use vs2022 professional version, i use to develop blazor apps, but happens with another kind of projects.
### The error does not bother me but I wanted to report it. In general terms, I think this is a great extension.
![image](https://user-images.githubusercontent.com/114080952/193267952-667b3096-f546-4f32-a4c7-498e5b9b624b.png)

**Comment by JiriZidek** [comment] 2022-10-02 23:26
Me too:
![image](https://user-images.githubusercontent.com/8578952/193480987-8966386c-98a1-4fed-b91b-d31daea0cc95.png)

**Comment by MattSty** [comment] 2022-10-03 11:18
Same here (inside a WPF project) ...not sure if that's not an issue with installed Resharper add in  ...do you have one installed?

**Comment by JiriZidek** [comment] 2022-10-03 11:34
> an issue with installed Resharper 
No Reshaper here, really conservative installation here (=almost everything just from MSFT or MSFT labs or MADS)

**Comment by madskristensen** [comment] 2022-10-03 15:58
Dupe of #28

**Closed by madskristensen** 2022-10-03 15:58 UTC
Labels: bug
