### ISSUE TITLE
Sometimes all code is colored

### ISSUE THREAD

**Issue by UlliBien** [madskristensen/RainbowBraces#35] opened 2022-10-17 06:05 UTC
Sometimes, especially when changing or entering code, the entire code is colored and not just the brackets.
![colored](https://user-images.githubusercontent.com/11003285/196100823-baec6bbc-27fb-4766-a2b3-fd91539ff3f8.png)
![sysinfo](https://user-images.githubusercontent.com/11003285/196101002-9dafe99d-fdcb-4d45-a1d2-f5516d0cfa54.png)

**Comment by NoahStahl** [comment] 2022-10-20 02:46
Also seeing this. For me, the scattered character colorization usually resolves after a scroll event.

**Comment by nnpcYvIVl** [comment] 2022-10-21 19:15
Same problem

**Comment by PiterGoCompany** [comment] 2022-10-28 05:49
The same in my case.
![image](https://user-images.githubusercontent.com/9109223/198512517-f07b0ecd-3de6-4b8c-954d-f3e6d93dc050.png)

**Comment by Zenathor** [comment] 2022-10-28 09:52
Duplicate of #28 ?

**Comment by madskristensen** [comment] 2022-10-28 17:37
@Zenathor, yes, this is a duplicate of #28

**Closed by madskristensen** 2022-10-28 17:37 UTC
Labels: bug
